server {
  listen 80 default_server;
  listen [::]:80 default_server;
  gzip_static always;
  gzip_proxied expired no-cache no-store private auth;
  gunzip on;
  client_max_body_size 2g;

  location = /app-config.js {
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store" always;
  }

  location /dicom-web/ {
    proxy_pass http://orthanc:8042/dicom-web/;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /wado/ {
    proxy_pass http://orthanc:8042/wado/;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
    add_header Cross-Origin-Resource-Policy same-origin;
  }
}
